# Generated by Django 3.2.6 on 2021-08-02 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='install_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
