# Generated by Django 3.2.6 on 2021-08-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0002_machine_install_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[(0, 'Unknown'), (1, 'Windows WeightLine'), (2, 'PLC WeightLine'), (3, 'SortLine'), (4, 'Gub Buncher')], default=0, max_length=32),
        ),
    ]
