# Generated by Django 3.2.6 on 2021-08-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0004_alter_machine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('weight_windows', 'Windows WeightLine'), ('weight_plc', 'PLC WeightLine'), ('sortline_windows', 'Windows SortLine'), ('sortline_plc', 'PLC SortLine'), ('gubbuncher', 'Gub-Buncher')], default='unknown', max_length=32),
        ),
    ]
