# Generated by Django 3.2.6 on 2021-08-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0005_alter_machine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='number',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
