# Generated by Django 3.2.6 on 2021-08-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svs', '0006_alter_machine_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svs.customer'),
        ),
    ]
